---
# Simulation Settings: 
 RUN_NUM: 1  # number of repeats/runs 
 OUT_FNAME: "_population_data.csv"  # extension for output data files
 SIM_MODE: 1  # mode of simulation to run

# Individual Settings:
 INNIT_AGE_RANGE: [ 10, 40 ]  # age range of individuals in the starting population
 MAX_AGE: 55  # age at which individual is removed from population 
 FERTILE_AGE_RANGE: [2, 40 ] # age range at which individuals can reproduce 
 REPRODUCE_RECOVER: 5  # number of days before individual can reproduce again 
 ALLOTTED_GENE_NUM: 5  # number of total genes an individual can have; max = 5
 
# Food Source Settings: 
 FOOD_UNIT: 4  # number of food unit per Food Source (1 unit = 1 individual) 
 INF_FOOD: True  # T: simulation has inifite food sources for individuals; F: finite food
 FOOD_SOURCE_AVAIL: 100  # number of food source, each producing FOOD_UNIT amount 
 PREDATOR_RISK: 0.03  # probability of a predator in the food source; ex: 0.02 = 1 in 50


# Other format examples - REMOVE LATER: 
 xmas-fifth-day:
   calling-birds: four
   french-hens: 3
   golden-rings: 5
   partridges:
     count: 1
     location: "a pear tree"
   turtle-doves: two